### ISSUE TITLE
showing error in downloading beef

### ISSUE THREAD

**Issue by anonymust1** [Hax4us/termux-x#12]
The following packages have unmet dependencies:
 beef-xss : Depends: ruby-dev but it is not installable
            Depends: libsqlite-dev but it is not installable
            Depends: libxslt-dev but it is not installable
E: Unable to correct problems, you have held broken packages.

plz tell

**Comment by Hax4us** [comment]
this repo is going to be delete so please use latest one
https://github.com/hax4us/termuxblack
