### ISSUE TITLE
build tree

### ISSUE THREAD

**Issue by twaik** [Hax4us/termux-x#9]
Hi. Can I see build scripts and patches used to build those packages? I tried to find those in https://github.com/Hax4us/x11-packages but failed.

**Comment by Hax4us** [comment]
I have but some of them ( hardly 2 or 3 packages ) are outdated now you will have to do little bit of editing in build scripts. I have not uploaded on GitHub so if you want I can give you directly by hangout or mail.

**Comment by twaik** [comment]
Can you please attach them here?

**Comment by twaik** [comment]
You can send them to twaikyont@gmail.com . Thanks.

**Comment by twaik** [comment]
Still did not receive your packages.

**Comment by twaik** [comment]
Got packages! Thank you very much!
